spring.application.name=factory

# DB ??
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/factory_db
spring.datasource.username=factory
spring.datasource.password=factory1234

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.mes.factory